hostname: identity.yas.local.com
backofficeRedirectUrl: http://backoffice.yas.local.com
storefrontRedirectUrl: http://storefront.yas.local.com
postgresql:
  username: yasadminuser
  password: admin

bootstrapAdmin:
  username: admin
  password: admin