domain: yas.local.com
postgresql:
  replicas: 1
  username: yasadminuser
  password: admin
kafka:
  replicas: 1
zookeeper:
  replicas: 1
elasticsearch:
  replicas: 1
  username: yas
  password: LarUmB3A49NTg9YmgW4=
keycloak:
  bootstrapAdmin:
    username: admin
    password: admin
  backofficeRedirectUrl: http://backoffice.yas.local.com
  storefrontRedirectUrl: http://storefront.yas.local.com
grafana:
  username: admin
  password: admin
redis:
  password: redis