apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
data:
  username: {{ .Values.bootstrapAdmin.username | b64enc }}
  password: {{ .Values.bootstrapAdmin.password | b64enc }}