global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - 'collector:8888'
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090