apiVersion: v1
kind: Secret
metadata:
  name: yas-postgresql-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  POSTGRESQL_USERNAME: {{ .Values.credentials.postgresql.username | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.credentials.postgresql.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: yas-elasticsearch-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  ELASTICSEARCH_USERNAME: {{ .Values.credentials.elasticsearch.username | b64enc }}
  ELASTICSEARCH_PASSWORD: {{ .Values.credentials.elasticsearch.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: yas-keycloak-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  KEYCLOAK_BACKOFFICE_BFF_CLIENT_SECRET: {{ .Values.credentials.keycloak.backofficeBffClientSecret | b64enc }}
  KEYCLOAK_STOREFRONT_BFF_CLIENT_SECRET: {{ .Values.credentials.keycloak.storefrontBffClientSecret | b64enc }}
  KEYCLOAK_CUSTOMER_MANAGEMENT_CLIENT_SECRET: {{ .Values.credentials.keycloak.customerManagementClientSecret | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: yas-redis-credentials-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.credentials.redis.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: yas-openai-api-key-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.credentials.openai.apiKey | b64enc }}