apiVersion: 1

datasources:
    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      editable: false
      jsonData:
        httpMethod: GET
      version: 1
      # jsonData:
      #   httpMethod: POST
      #   exemplarTraceIdDestinations:
      #     - datasourceUid: webstore-traces
      #       name: trace_id
      #     - url: http://localhost:8090/jaeger/ui/trace/$${__value.raw}
      #       name: trace_id
      #       urlDisplayLabel: View in Jaeger UI
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo:3200
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      apiVersion: 1
      uid: tempo
      jsonData:
          httpMethod: GET
          tracesToLogs:
              datasourceUid: 'loki'
          serviceMap:
            datasourceUid: 'prometheus'
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      orgId: 1
      url: http://loki:3100
      basicAuth: false
      isDefault: false
      version: 1
      editable: false
      apiVersion: 1
      jsonData:
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: traceid":"([a-f0-9\-]+)
          name: TraceID
          url: $${__value.raw}
