backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-{{service}}
    tag: latest

  nameOverride: {{service}}
  fullnameOverride: {{service}}
  databaseName: {{service}}

  ingress:
    enabled: true
    host: api.yas.local.com
    path: /{{service}}