opentelemetryCollectorConfig:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    loki:
      protocols:
        http:
          endpoint: 0.0.0.0:3500
      use_incoming_timestamp: true
  processors:
    batch:
    attributes:
      actions:
        - action: insert
          key: loki.attribute.labels
          value: namespace,container,pod,level,traceId
        - action: insert
          key: loki.format
          value: raw

  exporters:
    logging:
      verbosity: detailed
    loki:
      endpoint: http://loki-gateway/loki/api/v1/push
    otlphttp:
      endpoint: http://tempo:4318
  service:
    pipelines:
      logs:
        receivers: [loki]
        processors: [attributes]
        exporters: [loki]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]