apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 8.8.1
  auth:
    fileRealm:
      - secretName: user-credentials-secret
  nodeSets:
    - name: node
      count: {{ .Values.elasticsearch.replicas }}
      config:
        node.store.allow_mmap: false
