kind: Secret
apiVersion: v1
metadata:
  name: user-credentials-secret
stringData:
  {{- $files := .Files }}
  users: |-
  {{- range tuple "filerealm/users" }}
    {{ $files.Get . }}
  {{- end }}
  users_roles: |-
    superuser:yas