name: release charts ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "k8s/charts/**"
      - ".github/workflows/charts-ci.yaml"

jobs:
  release-charts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Update dependency
        run: |
          helm repo add stakater https://stakater.github.io/stakater-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: k8s/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"